### ISSUE TITLE
Popper content isn't near the button and jumped when button inside <foreignObject> of SVG on Android

### ISSUE THREAD

**Issue by namlq93** [popperjs/popper-core#1104]
## Current Behavior 😯

Popper content isn't near the button and jumped when button inside <foreignObject> of SVG on **Android**

![android](https://user-images.githubusercontent.com/41458989/81511494-0fc74c00-9344-11ea-9ee3-242e1b675537.PNG)

## Expected Behavior 🤔

It should be like this:
![PC](https://user-images.githubusercontent.com/41458989/81511596-b3186100-9344-11ea-844c-8b6cd3eb2551.PNG)
It works great on pc and ios, but android doesn't.

## Steps to Reproduce 🕹

You can see my example here and run on google chrome of android: https://codesandbox.io/s/material-demo-icwpd?file=/demo.js

**Comment by FezVrasta** [comment]
What Android version and which browser?

**Comment by namlq93** [comment]
> What Android version and which browser version?

I'm using android 10 and google chorme ver 81.

**Comment by FezVrasta** [comment]
I didn’t notice you are using v1, please upgrade to v2 and let me know if it’s still a problem

**Comment by ardcore** [comment]
This issue is present in v2 as well, and is not specific to android - happens in chrome 81 on desktop linux too (but doesn't happen in firefox)

**Comment by FezVrasta** [comment]
Great, may you please post a repro sandbox so that I can take a look?

**Comment by ardcore** [comment]
@FezVrasta sure: https://jsfiddle.net/e2r8501a/

**Comment by namlq93** [comment]
It seems to be related to the function `getBoundingClientRect()`. I created an issue on [bugs.chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1082016#c2). And they  linked to [the issue](https://bugs.chromium.org/p/chromium/issues/detail?id=738022).

**Comment by FezVrasta** [comment]
Cool, from what I understand we can't do much to fix this, it's a browser bug.

**Comment by ardcore** [comment]
As far as I understand, I could hack around this issue by using a modifier function (shift/offset) in which I would (after doing browser detection) revert the incorrectly applied devicePixelRatio:
```js
shift: {
    fn: (d) => {
      if (!d.popper) {
        d.offsets.reference.left /= window.devicePixelRatio;
        d.offsets.reference.top /= window.devicePixelRatio;
      }
      return d;
    }
  },
```

this actually positions my popups perfectly in chrome, but the huge downside is that I lose the "flip" functionality. @FezVrasta any advice/idea on to apply a similar fix without disabling flipping?

(the other idea would be to use `virtualElement` as a `referenceObject`, but since I'm using popper indirectly (via blueprintjs) it's not possible in my case)

**Comment by FezVrasta** [comment]
I don't have any Linux device to reproduce the problem so I can't play with it first hand.

You could try to run your custom modifier as soon as possible, and patch the `state.rects.reference` values. Doing so the rest of the modifiers should read the patches values and work as expected.

**Comment by ardcore** [comment]
Further investigation revealed that this bug is also happening on chrome@windows (not sure about mac), and is present when `window.devicePixelRatio` is not equal to `1`. You could probably emulate this by using custom zoom settings in your browser.

I wasn't able to go around this using custom modifiers - it seems that, for some reason, even using custom modifier with `order: 1` disables the "flip" modifier (or at least does something that prevents the flip modifier from working correctly).

As of now, the only working solution I came up with is monkey-patching `getBoundingClientRect`:
```js

if (window.chrome) {
  HTMLElement.prototype.getBoundingClientRect = function() {
    const rect = Element.prototype.getBoundingClientRect.call(this);
    if (this.closest('foreignObject')) {
      return {
        x: rect.x / window.devicePixelRatio,
        y: rect.y / window.devicePixelRatio,
        left: rect.left / window.devicePixelRatio,
        top: rect.top / window.devicePixelRatio,
        width: rect.width / window.devicePixelRatio,
        height: rect.height / window.devicePixelRatio,
        right: rect.right / window.devicePixelRatio,
        bottom: rect.bottom / window.devicePixelRatio,
      };
    }
    return rect;
  };
}
```
This aligns popups perfectly, but the downside is that it may have a big performance penalty in some scenarios due to the additional `parents()` call.

**Comment by mifonBejenari** [comment]
I have the same issue in Chrome and Safari.
I use [tippyjs-react](https://github.com/atomiks/tippyjs-react) and when I ZoomIn/ZoomOut page my tooltips jumps:

1. without zooming:
<img width="304" alt="Zoom 100%" src="https://user-images.githubusercontent.com/28762959/82824493-2330f600-9eb2-11ea-8a17-b0348b5e219a.png">

2. Zoom 90%:
<img width="269" alt="zoom 90%" src="https://user-images.githubusercontent.com/28762959/82824566-3e9c0100-9eb2-11ea-9fea-a21f592dacb2.png">

@ardcore , Your solution breaks tooltip in my case.
