### ISSUE TITLE
Initial Popper positioning is wrong when using Webpack - window resize required to fix it

### ISSUE THREAD

**Issue by alexsorinsky** [popperjs/popper-core#1109]
### CodeSandbox demo

**it appears only when using webpack (online codesandbox works as expected)**

### Steps to reproduce the problem

1. npm i @popperjs/core
2. import { createPopper } from '@popperjs/core'
3. the code (just try from https://popper.js.org/docs/v2/tutorial/ and add some centering for the button):
```pug
div.mt-5.mb-5
	.w-50.mx-auto.text-center
		button#btn(aria-describedby="tooltip") The button with popover
		#tooltip(role="tooltip") Tooltip text goes here <div id="arrow" data-popper-arrow></div>

```

```javascript
const btn = document.querySelector('#btn')
const tooltip = document.querySelector('#tooltip')

const popper = Popper.createPopper(btn, tooltip, {
	placement: "bottom",
})
popper.update()

```

### What is the expected behavior?
should been positioned as expected

### What went wrong?

First initial position of the Popper looks like this:
![](https://i.imgur.com/KdwGYdW.png)

and the rendered DOM Node:
```html
<div class="mt-5 mb-5">
	<div class="w-50 mx-auto text-center">
		<button id="btn" aria-describedby="tooltip">The button with popover</button>
		<div id="tooltip" role="tooltip" data-popper-placement="bottom"
		     style="position: absolute; left: 0px; top: 0px; margin: 0px; right: auto; bottom: auto; transform: translate(18px, 29px);">Tooltip text goes here
			<div id="arrow" data-popper-arrow="" style="position: absolute; left: 0px; transform: translate(70px, 0px);"></div>
		</div>
	</div>
</div>
```

### Any other comments?
but if we try to resize browser's window a little, the tooltip will be positioned correctly:
![](https://i.imgur.com/BsDUxej.png)

and rendered DOM Node's styles are correct now:

```html
<div class="mt-5 mb-5">
	<div class="w-50 mx-auto text-center">
		<button id="btn" aria-describedby="tooltip">The button with popover</button>
		<div id="tooltip" role="tooltip" data-popper-placement="bottom"
		     style="position: absolute; left: 0px; top: 0px; margin: 0px; right: auto; bottom: auto; transform: translate(560px, 78px);">Tooltip text goes here
			<div id="arrow" data-popper-arrow="" style="position: absolute; left: 0px; transform: translate(76px, 0px);"></div>
		</div>
	</div>
</div>

```

**Comment by FezVrasta** [comment]
CodeSandbox uses webpack too, and also our documentation website, together with a lot of apps I built.

The issue must be in your own code, but without a repro it’s impossible to find the problem. Consider asking this question on StackOverflow

**Comment by TheMangoTrain** [comment]
I had this same issue as OP.

However, our setup is a bit more complicated. We have Popper.js abstracted into a component (a wrapper) we're calling "Flyout", which we load and use dynamically throughout our large app. This gives us the benefit to swap popout libraries (like Tippy instead of Popper) and conveniently run unrelated logic when a popout occurs.

**Problem:**
Early in the lifecycle, Popper wasn't provided the values it needed for positioning on initial render. In our case, our components may not be fully rendered by the time Popper is initialized.

**Replicate:**
Here's a basic example in Codesandbox:
https://codesandbox.io/s/vue-js-popover-forked-gcthx?file=/src/components/Flyout.vue

1. Click 'Action 2' or 'Action 3'. Notice the popout occurs slightly lower (it should be vertically-centered of the parent when 'right' positioned).
2. Slightly move the browser window (or code editor pane). Notice the popout now appears in the correct place (vertically-center to the button).

**Solution:**
We listen for updates to our `show` prop in our popout component, and when that happens, we tell Popper to update itself. This works well because by the time the user clicks a button, our interface is fully rendered and Popper has all the values it needs. On this note, there may be other reasons to make Popper update itself too e.g. content changes externally or internally, etc.

https://codesandbox.io/s/vue-js-popover-forked-bsbw9?file=/src/components/Flyout.vue

In our Vue app, we watch the show prop, and do something accordingly:
```
  watch: {
    'show' : function(newVal, oldVal) {

        // We do stuff only if show is true, and we're not already showing it
        if(newVal === true && newVal !== oldVal) {
          console.log("Got show event!")
          
          // Tell Popper to update itself
          this.popperInstance.update()
        }
    }
  }
```

**Future:**
Instead of the above 'band-aid' solution, we may examine waiting to initialize Popper only when all relevant components are finished loading, so that Popper gets the values it needs. This would be the more elegant/proper way.
