### ISSUE TITLE
Popper version 2.6.0 is still showing 2.4.0 in package.json

### ISSUE THREAD

**Issue by akshayp660** [popperjs/popper-core#1205]
installing popperjs/core is still causing error for bootstrap 5 as the version in package.json shows 2.4.0 instead of 2.6.0

**Comment by XhmikosR** [comment]
I guess @FezVrasta the issue is valid and it'll be fixed with the next version bump.

**Comment by FezVrasta** [comment]
Hi, I'll take care of it today, thanks for the reminder

**Comment by FezVrasta** [comment]
So, on npm the version is correct.

https://unpkg.com/browse/@popperjs/core@2.6.0/package.json
![image](https://user-images.githubusercontent.com/5382443/107637289-2fdac180-6c6e-11eb-9f5a-b4939fe5bfa2.png)

The problem is only on Git, because the automatic deployment tool I use doesn't write back to the repo when a new version is published.

What's the problem you are having with the outdated version in Git? Why do you care about it?

**Comment by XhmikosR** [comment]
Personally, I have no issue, just noticed that the issue is true, but only on git.

**Comment by FezVrasta** [comment]
What's the Bootstrap error @akshayp660 is talking about? If it's not a real issue please let me know so I can close this.
