### ISSUE TITLE
Tether doesn't work with altAxis

### ISSUE THREAD

**Issue by Akryum** [popperjs/popper-core#1242]
### CodeSandbox demo

https://codesandbox.io/s/fancy-sea-mpxoo

### Steps to reproduce the problem

1. Scroll on the preview

### What is the expected behavior?

The popper should tether to the reference.

### What went wrong?

The popper is sticking to the boundary.

### Any other comments?

Note how `altAxis` and `tether` are enabled:

```js
createPopper(button, tooltip, {
  placement: "bottom",
  modifiers: [
    {
      name: "preventOverflow",
      options: {
        altAxis: true,
        tether: true
      }
    }
  ]
})
```

**Comment by FezVrasta** [comment]
I'm not sure what are you trying to achieve, it seems to work correctly, the tooltip never leaves the viewport.

**Comment by Akryum** [comment]
Shouldn't the `tether: true` option make sure that both objects stay together? It works for the main axis but not for the alt axis.

**Comment by Akryum** [comment]
You can try setting the placement to `right` to try it on the main axis.

**Comment by panzarino** [comment]
This issue still has not been fixed in the latest release - I did some work on fixing this (and got it working for my use case that I was testing) but couldn't quite get it past the finish line (still doesn't properly handle `tetherOffset` and `offsetModifierValue`. The logic around calculating the `tetherMin` and `tetherMax` in my fix is illogical as well (again, only tested on a single use case) so that probably needs to be fixed but I'll leave it here if someone wants to fully implement it (or could provide me with some direction to do so myself) - https://github.com/panzarino/popper-core/commit/9786a4f0782332dcf1cb9f2485a649d399f82bdd
