### ISSUE TITLE
autoUpdate does not always work when floating element is portaled

### ISSUE THREAD

**Issue by mihkeleidast** [popperjs/popper-core#1618]
Reproduction: https://codesandbox.io/s/adoring-lake-p7e0ps?file=/src/App.tsx

If the floating element is wrapped in a `FloatingPortal`, the autoUpdate feature does not seem to always work properly. In the reproduction, if you resize the browser viewport, the Tooltip part is not repositioned.

https://user-images.githubusercontent.com/1892091/162899673-d1904be2-0e28-45aa-ac22-e3e2f4829706.mp4

If I render the floating element conditionally, it seems to work (see https://codesandbox.io/s/affectionate-scott-kbyopd?file=/src/App.tsx) - but in my actual code that does not seem to make a difference.

I'm not sure if I'm missing anything, as the more complex Dropdown and similar examples from the docs are working.

**Comment by atomiks** [comment]
It looks like you need to use `refs.floating.current` as a dependency in this case. The reason is the FloatingPortal generates 2 renders, but the floating element doesn't exist by the time the effect in your component is called.

The reason it works in the docs is because they use `open &&` and pass that as a dependency, which happens after the FloatingPortal double render happens
