### ISSUE TITLE
CSS Positioning Discrepancy Causing Uniform Expansion Challenge During Migration from PopperJs to FloatingUi

### ISSUE THREAD

**Issue by a7medm7med** [popperjs/popper-core#2644]
I am currently facing a migration challenge from PopperJs to FloatingUi due to a fundamental difference in the handling of CSS positioning properties between the two systems.

In the current implementation (PopperJs), the CSS `bottom` property is utilized when the popup is positioned above the anchor element, and the `top` property is used when the popup is below the anchor element. However, in FloatingUi, this behavior differs significantly. The positioning in FloatingUi is consistent, relying solely on the CSS `top` property whether the popup is above or below the anchor element.

This divergence is causing a specific issue, especially when expanding the height of the popup. In FloatingUi, the expansion occurs uniformly from `top` to `bottom`, while in PopperJs, the expansion direction depends on the popup's relative position to the anchor.

So any suggestions?

**Comment by atomiks** [comment]
You can solve this by making the floating element a wrapper around a child whose height changes from 0 to auto, while the floating element's height uses the child's natural height immediately upon mounting, leaving it static. That way the floating element's layout is positioned correctly immediately, while the child can animate without any of the issues mentioned.

**Comment by atomiks** [comment]
[Here's a demo of the above](https://codesandbox.io/p/sandbox/jolly-estrela-f6msn7?file=%2Fsrc%2FApp.js%3A64%2C33). The grey box is the positioned floating element (will be transparent in real use) which prevents it from flipping around due to resizing, since its layout is static. The child animates smoothly based on the placement. Change `[...Array(5)]` to `[...Array(10)]` to see bottom vs top placement behavior.

Furthermore, it's technically possible to replicate Popper's adaptive side behavior with a custom middleware, but it's a bit complicated (and it was also the source of many bugs, and has limitations). The source for that is here: https://github.com/floating-ui/floating-ui/blob/92195083958c9496988ed4526b82b75b7256b5a4/src/modifiers/computeStyles.js#L94-L141
