### ISSUE TITLE
Flip modifier does not use fallbackPlacements and overflows when there is room to flip

### ISSUE THREAD

**Issue by alexkrautmann** [popperjs/popper-core#993]
### CodePen demo

https://codesandbox.io/s/inspiring-cherry-4nsgg

You need to make any change (e.g. whitespace) in the JS file for the codesandbox to work. I'm not sure why this is happening.

### Steps to reproduce the problem

1. Create a popper with `placement: left` and flip modifier option `fallbackPlacements: ["bottom", "top"]`.
2. Use the popper in a dom node that has `overflow: scroll`.
3. Scroll to a position where the fallback placements should be used

### What is the expected behavior?

The popper should respect the fallbackPlacements.

### What went wrong?

The popper stays at the initial placement of left, overflowing the container.

### Any other comments?

The codesandbox above is fairly stripped down from where I am seeing this issue. Some differences are that I am using `strategy: fixed` and that my popper is placed directly under `<body>` in order to avoid parent css conflicts. I am also passing options to the preventOverflow and arrow modifiers. As far as I can tell, the preventOverflow modifier is working properly in this same scenario. Both flip and preventOverflow modifiers work as expected using popper.js@1 with an equivalent configuration.

**Comment by atomiks** [comment]
In v2 the new default is `"clippingParents"`, which means, "scrolling containers that will cut the popper off". The scrolling container in the CodeSandbox won't cut the popper off, so it won't flip or be prevented from relative to it. You can specify `boundary` to be the scrolling element if you want that behavior.

In v1 the default was `"scrollParent"` which was the reference's scroll parent, but this was not a good default, because when the container was small and couldn't fit the popper, it caused overlapping positioning problems. While `altAxis` is no longer true by default (no overlapping), it may still flip to an unexpected side, and the positioning problems will occur again if it's enabled, without an obvious cause.

Also, we don't recommend using `fixed` as a strategy unless the reference element is actually fixed, because Safari isn't great with it currently.

**Comment by alexkrautmann** [comment]
This might be something to mention in the migration guide, as it is a breaking change from v1.

Also, I've actually tried setting the border to the the the popper internal state reference scrollParents inside a modifier, which did not work. Let me try to repro this as well. 

Also, when you say this:

> The scrolling container in the CodeSandbox won't cut the popper off, so it won't flip or be prevented from relative to it.

Why wouldn't the scrolling container cut the popper off? It has an overflow set on it, so I would think the child popper node should not overflow it.

**Comment by FezVrasta** [comment]
Not all the `overflow: scroll` containers clip absolutely positioned elements.

**Comment by alexkrautmann** [comment]
I'm using popper in a component library, and one of the great things about popper v1 is that I don't need to pass a boundary node around unless I want a custom boundary. This is nice because the component library is react, so its preferable not to have to hold onto a dom node to pass around components and into the where the consumer needs to use a tooltip. Being able to just import a component/hook and use it without much configuration is a huge win with popper v1.

I'm trying not to venture into "support thread" territory, but I'm interested in some input on how to proceed.

1) Is there any plan to support the older "scrollParent" boundary going forward? I could see making it another option but still applying `clippingParents` as a default.
2) If not, is this something you think could be handled by writing a custom modifier?

**Comment by FezVrasta** [comment]
Why would you like to use scroll parent as default boundary? That’s surprising for the user, users want to have tooltips positioned in the least surprising position, clipping parent allows to achieve that

**Comment by alexkrautmann** [comment]
I'm not suggesting that popper use `clippingParents` as a default. However, I would like to use scrollParent as a default for the tooltip in the component library I am working on.

One main reason In want to do this is to avoid requiring the user of the tooltip to have to worry about passing a dom node around the component tree.

The main use case here is for toottips in the main page content when that page content is a scrollable div that could be anywhere on the page. You could pass the prop down from the root using prop-drilling, store a reference in context, or storing the reference outside of react entirely.

Another similar use case is in various dialogs/modals that could be anywhere on the page and even consume components that themselves consume tooltip/popper. For example, if you have a form in a modal, you might want tooltips to provide information about the fields. These fields might be general re-usable fields that consume the tooltip. Here, you would need to store the ref of the scrollable modal, pass it into each Field component, which itself passes the ref into the tooltip. This example is only a few levels of prop drilling, but it could be much more. If you used that same shared Field component outside of a modal, now you would have to pass the original root boundary reference into the field instead of the modal reference.

At the end of the day, I want to avoid the user of my component having to worry about the implementation of popper/tooltip in order to use it for basic cases. Having to know about boundaries/refs/scrollParents/clippingParents etc. can be a bit much to have to deal with just to use a tooltip. To be clear, I still want to provide the flexibility to override any popper option, but the general case should be dead simple to use in my opinion. This is exactly how it worked in popper v1, which ended up removing a good amount of complexity compared to most tooltip solutions I've seen in react.

**Comment by atomiks** [comment]
The thing is `"clippingParents"` is supposed to be a good default. Why do you want to change it in the first place? Your component library will be partially broken by default in some ways and the consumer of it won't know why...

I'd only ever suggest using scrollParent as an escape hatch.  We could add `altBoundary` as an option for `flip` / `preventOverflow` (which means use `reference` `"clippingParents"` in this context — this is smarter than scrollParent but works the same effectively), which has very little cost since `detectOverflow` already supports it.
